### ISSUE TITLE
Bitrarray has no attribute lenght

### ISSUE THREAD

**Issue by Laululytia** [Mizogg/Hunting-with-PyQt5#1]
>py QT_main.py
Traceback (most recent call last):
  File "C:\Users\Hp\Desktop\Hunting-with-PyQt5-main\QT_main.py", line 10, in <module>
    bloom_filterbtc = BloomFilter.load(fp)
  File "C:\Python310\lib\site-packages\bloomfilter\bloomfilter.py", line 40, in load
    assert bloom_filter.__filter.length() == filter_size or bloom_filter.__filter.length() == filter_size + (
AttributeError: 'bitarray.bitarray' object has no attribute 'length'

**Comment by Mizogg** [comment]
Please run the command's 
pip install simplebloomfilter
pip install bitarray==1.9.2

Make sure you running the newest version of Python 3.11
